remove redundant step (#291)
follow-up on https://github.com/insightsengineering/tlg-catalog/pull/290

no need to clean-up assets if assets downloads is disabled

fixes errors in docs CI:
https://github.com/insightsengineering/tlg-catalog/actions/runs/11989043816
```
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file './book/_site/site_libs/quarto-contrib/shinylive-0.9.1/shinylive/webr/packages/metadata.rds', probable reason 'No such file or directory'
Execution halted
Error: Process completed with exit code 1.
```